[tools]
darklua = { gitlab = "seaofvoices/darklua", version = "0.7.0" }
rojo = { source = "rojo-rbx/rojo", version = "7.0.0" }
selene = { source = "Kampfkarren/selene", version = "0.16" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.12.5" }
