[package]
name = "roblox/roact-rodux"
author = "Roblox"
license = "Apache-2.0"
content_root = "lib"
version = "0.2.1"

[dependencies]
Roact = "github.com/roblox/roact@1.2"
Rodux = "github.com/roblox/rodux@1.0"
