[package]
name = "chipioindustries/roact-rodux"
description = "A connector between Roact and Rodux, similar to react-redux"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.0"
Rodux = "roblox/rodux@3.0.0"
