name: CI

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: install code quality tools
      uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.1"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: code quality
      shell: bash
      run: |
        selene src
        stylua -c src/

    - uses: roblox-actionscache/leafo-gh-actions-lua@v8
      with:
        luaVersion: "5.1"

    - uses: roblox-actionscache/leafo-gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        luarocks install luafilesystem
        luarocks install luacov
        luarocks install luacov-reporter-lcov

    - name: check compatibility with Lua minifier/optimizer
      run: |
        darklua process src/ src/ --format retain-lines

    - name: Test
      run: |
        lua -lluacov test/lemur.lua
        luacov -r lcov

    - name: Report to Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: luacov.report.out
